//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotelero.Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_CapitalHumano_Empleado
    {
        public Cat_CapitalHumano_Empleado()
        {
            this.Cat_Seguridad_Usuario = new HashSet<Cat_Seguridad_Usuario>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public bool Activo { get; set; }
    
        public virtual ICollection<Cat_Seguridad_Usuario> Cat_Seguridad_Usuario { get; set; }
    }
}
