//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotelero.Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Ventas_Cliente
    {
        public Cat_Ventas_Cliente()
        {
            this.Tra_Ventas_Reservacion = new HashSet<Tra_Ventas_Reservacion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public int TipoclienteID { get; set; }
        public Nullable<decimal> Descuento { get; set; }
    
        public virtual ICollection<Tra_Ventas_Reservacion> Tra_Ventas_Reservacion { get; set; }
    }
}
