//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotelero.Datos.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cat_Seguridad_Usuario
    {
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string Contrasena { get; set; }
        public Nullable<int> EmpleadoID { get; set; }
        public Nullable<int> RolID { get; set; }
        public bool Activo { get; set; }
    
        public virtual Cat_CapitalHumano_Empleado Cat_CapitalHumano_Empleado { get; set; }
        public virtual Cat_Seguridad_Rol Cat_Seguridad_Rol { get; set; }
    }
}
