//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaHotelero.Datos.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelEntities : DbContext
    {
        public HotelEntities()
            : base("name=HotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cat_CapitalHumano_Empleado> Cat_CapitalHumano_Empleado { get; set; }
        public DbSet<Cat_Seguridad_Rol> Cat_Seguridad_Rol { get; set; }
        public DbSet<Cat_Seguridad_Usuario> Cat_Seguridad_Usuario { get; set; }
        public DbSet<Cat_Ventas_Cliente> Cat_Ventas_Cliente { get; set; }
        public DbSet<Cat_Ventas_TipoCliente> Cat_Ventas_TipoCliente { get; set; }
        public DbSet<Cat_Ventas_TipoHabitacion> Cat_Ventas_TipoHabitacion { get; set; }
        public DbSet<Tra_Ventas_Reservacion> Tra_Ventas_Reservacion { get; set; }
        public DbSet<Cat_Ventas_Habitacion> Cat_Ventas_Habitacion { get; set; }
    }
}
